import Head from 'next/head'

export default function Home() {
  return (
    <div>
      <Head>
        <title>my Super Portfolio</title>
        <meta name="description" content="Generated by River" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <h1> My Portfolio</h1>
    </div>
  )
}
